version: '3.8'

services:
    database:
        image: browsebox-mysql
        container_name: browsebox-database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: browsebox
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - .:/database/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
        networks:
            development:
                ipv4_address: 192.168.92.20
networks:
    development:
        ipam:
            driver: default
            config:
                - subnet: "192.168.92.0/24"
